# Generated by Django 3.0.7 on 2020-07-04 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_auto_20200704_1603'),
        ('Product', '0002_auto_20200701_1559'),
        ('InvoiceList', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderProduct',
            new_name='ProductOrder',
        ),
    ]
