# Generated by Django 3.0.7 on 2020-07-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceList', '0002_auto_20200704_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='AmountTaken',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='Discount',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
