# Generated by Django 3.0.7 on 2020-07-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_auto_20200704_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='BankName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ChequeNo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='PlatformName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='TransactionId',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
